/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aryan
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mov = new javax.swing.JButton();
        show = new javax.swing.JButton();
        addmov = new javax.swing.JButton();
        addshow = new javax.swing.JButton();
        remmov = new javax.swing.JButton();
        remshow = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setText("Dashboard");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 270, 110));

        mov.setText("Movies");
        mov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movActionPerformed(evt);
            }
        });
        getContentPane().add(mov, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 180, 60));

        show.setText("Shows");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 200, 190, 60));

        addmov.setText("Add Movie");
        addmov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmovActionPerformed(evt);
            }
        });
        getContentPane().add(addmov, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 180, 70));

        addshow.setText("Add Show");
        addshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addshowActionPerformed(evt);
            }
        });
        getContentPane().add(addshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, 190, 70));

        remmov.setText("Remove Movie");
        remmov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remmovActionPerformed(evt);
            }
        });
        getContentPane().add(remmov, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 190, 70));

        remshow.setText("Remove Show");
        remshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remshowActionPerformed(evt);
            }
        });
        getContentPane().add(remshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 190, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/1398.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 3650, 4970));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void movActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movActionPerformed
        Movies mov= new Movies();
        mov.setVisible(true);
    }//GEN-LAST:event_movActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        Shows show= new Shows();
        show.setVisible(true);
    }//GEN-LAST:event_showActionPerformed

    private void addmovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmovActionPerformed
        addmovie addmov= new addmovie();
        addmov.setVisible(true);
    }//GEN-LAST:event_addmovActionPerformed

    private void addshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addshowActionPerformed
        addshow addshow= new addshow();
        addshow.setVisible(true);
    }//GEN-LAST:event_addshowActionPerformed

    private void remmovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remmovActionPerformed
        removemovie remmov = new removemovie();
        remmov.setVisible(true);
        
    }//GEN-LAST:event_remmovActionPerformed

    private void remshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remshowActionPerformed
        removeshow remshow= new removeshow();
        remshow.setVisible(true);
    }//GEN-LAST:event_remshowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addmov;
    private javax.swing.JButton addshow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mov;
    private javax.swing.JButton remmov;
    private javax.swing.JButton remshow;
    private javax.swing.JButton show;
    // End of variables declaration//GEN-END:variables
}
