/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aryan
 */

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.sql.Statement;

public class removemovie extends javax.swing.JFrame {

    /**
     * Creates new form removemovie
     */
    public removemovie() {
        initComponents();
        setDefaultCloseOperation(removemovie.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rmov = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        can = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DELEAT A RECORD ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 234, 52));

        rmov.setText("REMOVE MOVIE");
        rmov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmovActionPerformed(evt);
            }
        });
        getContentPane().add(rmov, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 295, 59));

        can.setText("CANCEL");
        can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canActionPerformed(evt);
            }
        });
        getContentPane().add(can, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, -1, -1));

        jLabel2.setText("ENTER MOVIE_ID ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 137, 59));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(838, 417, 177, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/1398.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -80, 8950, 6140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rmovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmovActionPerformed
        String url="jdbc:mysql://localhost:3306/ott?useSSL=false";
        String mysqluser="root";
        String mysqlpwd= "root";
        int input= Integer.parseInt(t1.getText());
        
        
        
        String query="delete from MOVIE_DETAILS where movie_id='"+input+"';";
        try {
               Connection conn= DriverManager.getConnection (url, mysqluser, mysqlpwd);
            Statement stm= conn.createStatement();
            int rows= stm.executeUpdate(query);
            if(rows>0)
            {
                JOptionPane.showMessageDialog(this, "movie removed from database");
            }
            else{
                JOptionPane.showMessageDialog(this, "no such movie in databsse");
            }
            stm.close();

               }
            catch (Exception e)
              { 
                  JOptionPane.showMessageDialog(this,e);
              
               }

    }//GEN-LAST:event_rmovActionPerformed

    private void canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canActionPerformed
        this.dispose();
    }//GEN-LAST:event_canActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(removemovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(removemovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(removemovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(removemovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new removemovie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton can;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton rmov;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
